Repository Code-Dabblers/MagicReads_BE, pull requests merged in 2020-10, with the labels that each got.

#1 model files, fetching DB collections working
  models/Chapter.js
  models/Stories.js
  models/Story.js
  models/User.js
  package-lock.json
  package.json
  routes/index.js
  server.js
Labels: add-feature

#3 user register and login functionality
  config/passport.js
  models/User.js
  package-lock.json
  package.json
  routes/index.js
  routes/story.js
  routes/user.js
  server.js
Labels: add-feature, hackoctoberfest-accepted

#22 Feature/read stories
  package-lock.json
  package.json
  routes/user.js
Labels: hackoctoberfest-accepted

#21 story routes handled
  routes/story.js
Labels: hackoctoberfest-accepted

#23 Fix/#issue 8
  config/db.js
  models/Story.js
  models/User.js
  package.json
  routes/search.js
  routes/story.js
Labels: hackoctoberfest-accepted

#24 Feature/update user settings
  routes/user.js
Labels: hackoctoberfest-accepted
